spring: 
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: turbine
      profile: dev
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")
